export const dummyPosts = [
  {
    title: "The Rise of Modern Football Tactics",
    content: "An in-depth look at how high-pressing systems have transformed the beautiful game in 2025...",
    category: "football",
    authorId: "kp_7890abc",
    authorName: "Letso Mogwera",
    authorImage: "",
    image: "",
    tags: ["Tactics", "Premier League", "Analysis"],
    published: true,
    createdAt: new Date("2025-01-10"),
  },
  {
    title: "UFC 310: The Championship Breakdown",
    content: "Evaluating the striking patterns and wrestling transitions of the main event fighters...",
    category: "fighting",
    authorId: "kp_1234xyz",
    authorName: "John Doe",
    authorImage: "",
    image: "",
    tags: ["MMA", "UFC", "Martial Arts"],
    published: true,
    createdAt: new Date("2025-01-12"),
  },
  {
    title: "The Evolution of the Step-Back Jumper",
    content: "How basketball stars are creating more space than ever before using advanced footwork...",
    category: "basketball",
    authorId: "kp_7890abc",
    authorName: "Letso Mogwera",
    authorImage: "",
    image: "",
    tags: ["NBA", "Skills", "Hoops"],
    published: false, // Draft mode
    createdAt: new Date("2025-01-15"),
  },
  {
    title: "Formula 1: Aerodynamics in 2026",
    content: "Exploring the upcoming regulation changes that will redefine racing speed and safety...",
    category: "racing",
    authorId: "kp_4567def",
    authorName: "Sarah Smith",
    authorImage: "",
    image: "",
    tags: ["F1", "Engineering", "Motorsport"],
    published: true,
    createdAt: new Date("2025-01-18"),
  }
];